# Generated by Django 2.1 on 2020-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblReportmenus',
            fields=[
                ('mnuid', models.AutoField(primary_key=True, serialize=False)),
                ('mnulvl', models.CharField(max_length=1)),
                ('mnucod', models.CharField(max_length=4)),
                ('mnuname', models.CharField(max_length=512)),
                ('mnudesc', models.TextField(blank=True, null=True)),
                ('rptlvl', models.CharField(blank=True, max_length=1, null=True)),
                ('rptpriv', models.CharField(blank=True, max_length=1, null=True)),
                ('rptname', models.CharField(blank=True, max_length=255, null=True)),
                ('rptlink', models.CharField(blank=True, max_length=1024, null=True)),
                ('mnustatus', models.CharField(blank=True, max_length=1, null=True)),
                ('istesting', models.CharField(blank=True, db_column='isTesting', max_length=1, null=True)),
                ('isproduction', models.CharField(blank=True, db_column='isProduction', max_length=1, null=True)),
                ('rptstatus', models.CharField(blank=True, db_column='rptStatus', max_length=50, null=True)),
                ('rptowner', models.CharField(blank=True, db_column='rptOwner', max_length=20, null=True)),
                ('rptlink1', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_reportmenus',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='reportmenu',
            old_name='desc',
            new_name='display_name',
        ),
    ]
